[build]
  publish = "site"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "DENY"

[[redirects]]
  from = "https://bumblebot.dev/*"
  to = "https://bumblebot.ai/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.bumblebot.dev/*"
  to = "https://bumblebot.ai/:splat"
  status = 301
  force = true
